name: Mirror_To_New_Repo

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'New repo url. e.g. https://github.com/gendloop/reponame.git'
        required: true
        default: 'https://github.com/gendloop/template-CompositeProject.git'

  schedule:
    - cron: '5 17 2 * *'

jobs:
  mirror_to_new_repo:
    if: github.repository == 'XiGeoAlgorithm/template-CompositeProject'
    runs-on: ubuntu-latest
    steps:
      - name: mirror-to-new-repo
        uses: gendloop/mirror-to-new-repo@v1.0.0
        with:
          repo: ${{ inputs.repo }}
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
